import type { Metadata } from 'next'

import './globals.css'

import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Nats Skeleton NextJS',
  description: 'Generated by create next app',
}

const sg = Inter({ subsets: ['latin'], display: 'swap' })

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={sg.className}>{children}</body>
    </html>
  )
}
